version: "3.1"

services:
#  addressesapi:
#    image: addressesapi:latest
#    container_name: addresses-api-service-container
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - db-dev.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
